### ISSUE TITLE
How do I install your build in my raspberry pi ?

### ISSUE THREAD

**Issue by jabulonboaz** [Dimeiza/Assistants#1]
Hello this is grate work, how do instal this build in my pi please?
What commands  and what scripts do I need to execute first ?
Can I use Raspbian Jessie lite?
Can I install this on a pi zero w and also have the respeaker leds change colours in both assistants ?
Will both GA and AVS start automatically at boot and if not how can I do that?

**Comment by Dimeiza** [comment]
Read README.md.
