### ISSUE TITLE
Help me please. [ERROR] Missing parameters!

### ISSUE THREAD

**Issue by qwexcom** [Dimeiza/Assistants#32]
I don't know how to fix them.
please help to me.
Thank you.

==============> SAVING CONFIGURATION FILE ==============

[ERROR] Missing parameters!
Usage: genConfig.sh <config.json file> <device_serial_number> <db path> <SDK Source Directory>
<output AlexaClientSDKConfig.json file> [-D<variable>=<value>]+
1) <config.json file> can be downloaded from developer portal and must contain the following:
   "clientId": "<OAuth client ID>"
   "productId": "<your product name for device>"
2) <device_serial_number> specifies the deviceInfo deviceSerialNumber in the output json file.
3) <db path> specifies the path to where the databases will be located.
4) <SDK Source Directory> specifies the root directory to where the avs-device-sdk source code is located.
5) <output AlexaClientSDKConfig.json file> output file
6) Configure different variables that can be used to fill up extra information in the final configuration. Avaiable variables are:
   "SDK_CONFIG_MANUFACTURER_NAME": The name of the device manufacturer. This variable is required.
   "SDK_CONFIG_DEVICE_DESCRIPTION": The description of the device. This variable is required.

**Comment by Dimeiza** [comment]
Avs-device-sdk has been updated(1.17), and new genconfig.sh didn't use properly in setup.sh of this prototype.
So I have added a new install script for Alexa and update install procedure in readme. 

I have confirmed it run successfully with my environment.
You can try a new install procedure for Alexa after remove old version of Assistants.
