### ISSUE TITLE
bash setupAssistantControl.sh error

### ISSUE THREAD

**Issue by ubu78** [Dimeiza/Assistants#34]
bash setupAssistantControl.sh
fatal: destination path 'snowboy' already exists and is not an empty directory.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libatlas-base-dev is already the newest version (3.10.3-8+rpi1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pyaudio is already the newest version (0.2.11-1+b2).
python3-pyaudio is already the newest version (0.2.11-1+b2).
sox is already the newest version (14.4.2+git20190427-1).
swig is already the newest version (3.0.12-2).
swig3.0 is already the newest version (3.0.12-2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyaudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Collecting spidev
  Using cached https://www.piwheels.org/simple/spidev/spidev-3.4-cp37-cp37m-linux_armv7l.whl (39 kB)
Requirement already satisfied: posix_ipc in /home/pi/Assistants/env/lib/python3.7/site-packages (1.0.4)
Collecting gpiozero
  Using cached gpiozero-1.5.1-py2.py3-none-any.whl (138 kB)
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.18.1-cp37-cp37m-linux_armv7l.whl (10.4 MB)
Collecting RPi.GPIO
  Using cached https://www.piwheels.org/simple/rpi-gpio/RPi.GPIO-0.7.0-cp37-cp37m-linux_armv7l.whl (69 kB)
Collecting colorzero
  Using cached colorzero-1.1-py2.py3-none-any.whl (33 kB)
Building wheels for collected packages: pyaudio
  Building wheel for pyaudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/Assistants/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1sb83nw8                                                                              
       cwd: /tmp/pip-install-984rasg8/pyaudio/                                                                                                                       
  Complete output (16 lines):                                                                                                                                        
  running bdist_wheel                                                                                                                                                
  running build                                                                                                                                                      
  running build_py                                                                                                                                                   
  creating build                                                                                                                                                     
  creating build/lib.linux-armv7l-3.7                                                                                                                                
  copying src/pyaudio.py -> build/lib.linux-armv7l-3.7                                                                                                               
  running build_ext                                                                                                                                                  
  building '_portaudio' extension                                                                                                                                    
  creating build/temp.linux-armv7l-3.7                                                                                                                               
  creating build/temp.linux-armv7l-3.7/src                                                                                                                           
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/Assistants/env/include -I/usr/include/python3.7m -c src/_portaudiomodule.c -o build/temp.linux-armv7l-3.7/src/_portaudiomodule.o                           
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory                                                                                  
   #include "portaudio.h"                                                                                                                                            
            ^~~~~~~~~~~~~                                                                                                                                            
  compilation terminated.                                                                                                                                            
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1                                                                                                 
  ----------------------------------------                                                                                                                           
  ERROR: Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio, spidev, colorzero, gpiozero, numpy, RPi.GPIO
    Running setup.py install for pyaudio ... error
    ERROR: Command errored out with exit status 1:
     command: /home/pi/Assistants/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_sowol3l/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Assistants/env/include/site/python3.7/pyaudio
         cwd: /tmp/pip-install-984rasg8/pyaudio/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    copying src/pyaudio.py -> build/lib.linux-armv7l-3.7
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-armv7l-3.7
    creating build/temp.linux-armv7l-3.7/src
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/pi/Assistants/env/include -I/usr/include/python3.7m -c src/_portaudiomodule.c -o build/temp.linux-armv7l-3.7/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or directory
     #include "portaudio.h"
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/pi/Assistants/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-984rasg8/pyaudio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_sowol3l/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Assistants/env/include/site/python3.7/pyaudio Check the logs for full command output.
make: Nothing to be done for 'all'.
cp: cannot stat 'snowboy/examples/Python3/snowboy-1.2.0b1-py2-none-any.whl': No such file or directory
mkdir: cannot create directory 'resources': File exists
fatal: destination path 'mic_hat' already exists and is not an empty directory.
fatal: destination path 'mic_hat_4' already exists and is not an empty directory.
mv: cannot stat 'alexa_led_pattern.py': No such file or directory
mv: cannot stat 'google_home_led_pattern.py': No such file or directory

**Comment by Dimeiza** [comment]
After performing following steps, you can retry setupAssistantControl.sh.

https://raspberrypi.stackexchange.com/questions/75031/cannot-install-pyaudio

**Comment by ubu78** [comment]
Thanks
