### ISSUE TITLE
Where have you defined http://127.0.0.1:3000 ? Need to be ale to change it to my local subnet IP

### ISSUE THREAD

**Issue by jabulonboaz** [Dimeiza/Assistants#8]
Where have you defined http://127.0.0.1:3000 ? 

Need to be ale to change it to my local subnet IP as I am doing this via SSH and the Pi is on IP 192.168.1.2 and that is the IP i defined in the AVS development web side at port 3000. 

Your kind support please. 
Thanks

**Comment by Dimeiza** [comment]
I haven't define it.
It have been specified by AVS Device SDK.

I recommend that you read Quick Start Guide of AVS Device SDK.
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide-with-Script

And follow this instruction in Quick Start Guide.
>IMPORTANT: The allowed origins under web settings should be http://localhost:3000 and https://localhost:3000. The return URLs under web settings should be http://localhost:3000/authresponse and https://localhost:3000/authresponse.
